### ISSUE TITLE
slac binaries are overwritten

### ISSUE THREAD

**Issue by lategoodbye** [qca/open-plc-utils#30]
The slac binaries evse and pev are overwritten by the binaries from the iso directory, if make install is called.

Possible solutions:
- only the binaries from the slac directory are installed
- only the binaries from the iso directory are installed
- the binaries in the iso directory must be renamed

**Comment by razzlefratz** [comment]
Sorry for the later response here. I am now working in San Jose. The SLAC protocol is a HomePlug Green PHY features discussed in that specification. The automotive folks had a interest for a while but wanted a tighter specification. The ISO folks took the idea and included it in ISO 15118. I have not followed any developments in over a year. If you are still interested I will try to fine out who is doing what.

**Comment by gimx** [comment]
I would really appreciate if you could follow this up. I believe it might be related the following issue.
I have a connection up and running to my EV, but it seems to ignore the CM_SLAC_PARM.CNF that is sent by the iso evse binary, since it keeps sending CM_SLAC_PARAM.REQ....

evse: slac_session: session.RunID 00:00:00:00:00:00:00:00
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:00:00:00:00:00
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC 00:00:00:00:00:00
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 1
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: evse_cm_set_key: --> CM_SET_KEY.REQ
evse: evse_cm_set_key: CM_SET_KEY.KEYTYPE 1
evse: evse_cm_set_key: CM_SET_KEY.MYNOUNCE AA:AA:AA:AA
evse: evse_cm_set_key: CM_SET_KEY.YOURNOUNCE 00:00:00:00
evse: evse_cm_set_key: CM_SET_KEY.PID 2
evse: evse_cm_set_key: CM_SET_KEY.PRN 0
evse: evse_cm_set_key: CM_SET_KEY.PMN 0
evse: evse_cm_set_key: CM_SET_KEY.CCoCAP 0
evse: evse_cm_set_key: CM_SET_KEY.NID 02:6B:CB:A5:35:4E:08
evse: evse_cm_set_key: CM_SET_KEY.NEWEKS 1
evse: evse_cm_set_key: CM_SET_KEY.NEWKEY B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
00000000 00 B0 52 00 00 01 B8 27 EB 56 8E 40 88 E1 01 08 ..R....'.V.@....
00000010 60 00 00 01 AA AA AA AA 00 00 00 00 02 00 00 00 `...............
00000020 00 02 6B CB A5 35 4E 08 01 B5 93 19 D7 E8 15 7B ..k..5N........{
00000030 A0 01 B0 18 66 9C CE E3 0D 00 00 00             ....f.......    

00000000 B8 27 EB 56 8E 40 F4 3E 61 2B D2 68 88 E1 01 09 .'.V.@.>a+.h....
00000010 60 00 00 01 60 F2 16 8D AA AA AA AA 02 00 00 FF `...`...........
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_set_key: <-- CM_SET_KEY.CNF
evse: evse_cm_set_key: CM_SET_KEY.RESULT 1
evse: evse_cm_set_key: CM_SET_KEY.MYNOUNCE 60:F2:16:8D
evse: evse_cm_set_key: CM_SET_KEY.YOURNOUNCE AA:AA:AA:AA
evse: evse_cm_set_key: CM_SET_KEY.PID 2
evse: evse_cm_set_key: CM_SET_KEY.PRN 0
evse: evse_cm_set_key: CM_SET_KEY.PMN 255
evse: evse_cm_set_key: CM_SET_KEY.CCoCAP 0
evse: slac_session: session.RunID 00:00:00:00:00:00:00:00
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:00:00:00:00:00
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 1
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnoccupiedState: Listening ...
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 54 64 80 35 3D 78 B4 1F 00 00 00 `....Td.5=x.....
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.APPLICATION_TYPE 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.SECURITY_TYPE 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.RunID 54:64:80:35:3D:78:B4:1F
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuiteSetSize 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuite [0] 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuite [1] 0
evse: evse_cm_slac_param: --> CM_SLAC_PARAM.CNF
00000000 00 7D FA 01 19 5C B8 27 EB 56 8E 40 88 E1 01 65 .}...\.'.V.@...e
00000010 60 00 00 FF FF FF FF FF FF 08 0A 00 00 00 00 00 `...............
00000020 00 00 00 00 54 64 80 35 3D 78 B4 1F 00 00 00 00 ....Td.5=x......
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: slac_session: session.RunID 54:64:80:35:3D:78:B4:1F
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:7D:FA:01:19:5C
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 2
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnmatchedState: Sounding ...
00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 54 64 80 35 3D 78 B4 1F 00 00 00 `....Td.5=x.....
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 54 64 80 35 3D 78 B4 1F 00 00 00 `....Td.5=x.....
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_start_atten_char: CM_START_ATTEN_CHAR.IND ?
evse: slac_session: session.RunID 54:64:80:35:3D:78:B4:1F
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:7D:FA:01:19:5C
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 1
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnoccupiedState: Listening ...
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 62 1D 9B 4F DD CA 21 23 00 00 00 `....b..O..!#...
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.APPLICATION_TYPE 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.SECURITY_TYPE 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.RunID 62:1D:9B:4F:DD:CA:21:23
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuiteSetSize 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuite [0] 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuite [1] 0
evse: evse_cm_slac_param: --> CM_SLAC_PARAM.CNF
00000000 00 7D FA 01 19 5C B8 27 EB 56 8E 40 88 E1 01 65 .}...\.'.V.@...e
00000010 60 00 00 FF FF FF FF FF FF 08 0A 00 00 00 00 00 `...............
00000020 00 00 00 00 62 1D 9B 4F DD CA 21 23 00 00 00 00 ....b..O..!#....
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: slac_session: session.RunID 62:1D:9B:4F:DD:CA:21:23
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:7D:FA:01:19:5C
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 2
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnmatchedState: Sounding ...
00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 62 1D 9B 4F DD CA 21 23 00 00 00 `....b..O..!#...
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 62 1D 9B 4F DD CA 21 23 00 00 00 `....b..O..!#...
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_start_atten_char: CM_START_ATTEN_CHAR.IND ?
evse: slac_session: session.RunID 62:1D:9B:4F:DD:CA:21:23
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:7D:FA:01:19:5C
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 1
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnoccupiedState: Listening ...
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 B5 FE 27 2E 18 B3 34 DA 00 00 00 `......'...4....
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.APPLICATION_TYPE 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.SECURITY_TYPE 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.RunID B5:FE:27:2E:18:B3:34:DA
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuiteSetSize 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuite [0] 0
evse: evse_cm_slac_param: CM_SLAC_PARAM.REQ.CipherSuite [1] 0
evse: evse_cm_slac_param: --> CM_SLAC_PARAM.CNF
00000000 00 7D FA 01 19 5C B8 27 EB 56 8E 40 88 E1 01 65 .}...\.'.V.@...e
00000010 60 00 00 FF FF FF FF FF FF 08 0A 00 00 00 00 00 `...............
00000020 00 00 00 00 B5 FE 27 2E 18 B3 34 DA 00 00 00 00 ......'...4.....
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: slac_session: session.RunID B5:FE:27:2E:18:B3:34:DA
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:7D:FA:01:19:5C
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 2
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnmatchedState: Sounding ...
00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 B5 FE 27 2E 18 B3 34 DA 00 00 00 `......'...4....
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

00000000 FF FF FF FF FF FF 00 7D FA 01 19 5C 88 E1 01 64 .......}...\...d
00000010 60 00 00 00 00 B5 FE 27 2E 18 B3 34 DA 00 00 00 `......'...4....
00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000030 00 00 00 00 00 00 00 00 00 00 00 00             ............    

evse: evse_cm_start_atten_char: CM_START_ATTEN_CHAR.IND ?
evse: slac_session: session.RunID B5:FE:27:2E:18:B3:34:DA
evse: slac_session: session.APPLICATION_TYPE 0
evse: slac_session: session.SECURITY_TYPE 0
evse: slac_session: session.RESP_TYPE 0
evse: slac_session: session.NUM_SOUNDS 8
evse: slac_session: session.TIME_OUT 10
evse: slac_session: session.NumGroups 0
evse: slac_session: session.AAG 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.MSOUND_TARGET 00:00:00:00:00:00
evse: slac_session: session.FORWARDING_STA 00:00:00:00:00:00
evse: slac_session: session.PEV_ID 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.PEV_MAC 00:7D:FA:01:19:5C
evse: slac_session: session.EVSE_ID BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB:BB
evse: slac_session: session.EVSE_MAC B8:27:EB:56:8E:40
evse: slac_session: session.RND 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
evse: slac_session: session.NMK B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.NID 02:6B:CB:A5:35:4E:08
evse: slac_session: session.original_nmk B5:93:19:D7:E8:15:7B:A0:01:B0:18:66:9C:CE:E3:0D
evse: slac_session: session.original_nid 02:6B:CB:A5:35:4E:08
evse: slac_session: session.state 1
evse: slac_session: session.sounds 0
evse: slac_session: session.limit 0
evse: slac_session: session.pause 0
evse: slac_session: session.chargetime 2
evse: slac_session: session.settletime 10
evse: slac_session: session.counter 0
evse: slac_session: session.flags 0x000E
evse: UnoccupiedState: Listening ...
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?
evse: evse_cm_slac_param: <-- CM_SLAC_PARAM.REQ ?

**Comment by razzlefratz** [comment]
I looked and the Makefile in the root folder only compiles and installs the slack folder. It used to compile and install both slac and iso15118 causing the last one to overwrite the first. I need to sudsy your printout but I need to ask if you have programmed one device as PEV and the other as EVSE using different PIBs ? If not I need explain how to do that. It is a pain the tools will not work unless that is done first.

**Comment by gimx** [comment]
Thanks for your prompt reply. For clarity the PEV is a REAL e-Golf (implementing ISO15118 I guess ;), hence no need to program a PIB to it. EVSE is a 6400 chipset. My question is whether the executable produced in the ISO folder are indeed standard compliant or not (any longer).

**Comment by razzlefratz** [comment]
OK. I think I understand. Two issues here.  1) The PEV and EVSE devices both have to be QCA7000 devices because SLAC protocol is not supported by firmware written fro other chipsets. I will verify that this has not changed in the last year or so.  2) QCA SLAC and ISO 15118 tools are identical, except from user-facing text. When I learned about ISO 15118, I found that the committee was recommending changes (variations) to the SLAC protocol. I wanted to support both variants. Folks were experimenting with SLAC but planning to use the ISO version. The latter has not progressed but we are free to make changes in one folder without disturbing the other.

The main differences between SLAC and ISO 15118, as I understand it, deals with message timing and tolerances. I have not followed the standards in over 18 months and there may be other changes I am not aware of. I read parts of the original recommendation and it cover a lot things besides the SLAC-like charging protocols.

Now that you raise this issue, I will enquire.
